version: "3.8"
services:
  jupyter-lab:
    container_name: jupyter-lab-dsa-cont
    hostname: jupyter-lab-dsa
    image: jupyter-lab-dsa-img
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        USER_HOST: ${USER} # Pass the host's user to the Dockerfile.
        UID_HOST: "${UID:-1000}"
        GID_HOST: "${GID:-1000}"

    environment:
      SHELL: /bin/bash
      JUPYTER_TOKEN: "foo" # Access the lab with the query string: ?token=foo

    volumes:
      - ../src:/home/${USER}/src # bind mount

    ports:
      - 8888:8888
